#!/usr/bin/env python3
"""nsgperf.py -- what gperf produces, without gperf.

NetSurf's build runs `gperf` over a keyword file to generate a perfect-hash
lookup. gperf is a build-HOST tool, not a target dependency: nothing it emits
needs a perfect hash to be *correct*, only to be fast, and the one table this
port needs is 110 HTML tag names.

So rather than add a package the build machine has to be told to install --
which is a dependency this project spends its time removing, not acquiring --
this emits the same interface over a sorted table and a binary search. Same
function name, same struct, same NULL-for-absent contract. `--ignore-case` is
honoured because HTML tag names are matched case-insensitively.

Two orders of magnitude fewer keywords than the point where a perfect hash
starts to matter, and the lookup is O(log n) on a 110-entry table behind a
parser that has already done more work per tag than this costs.

  nsgperf.py input.gperf output.c
"""
import sys


def parse(path):
    """The subset of the gperf format NetSurf actually writes: %-directives,
    an optional %{ ... %} verbatim block, then `keyword, VALUE` lines after
    the %% separator."""
    directives, verbatim, keywords = {}, [], []
    section, in_verbatim = 0, False
    for line in open(path, encoding="utf-8"):
        raw = line.rstrip("\n")
        if in_verbatim:
            if raw.strip() == "%}":
                in_verbatim = False
            else:
                verbatim.append(raw)
            continue
        if section == 0:
            if raw.strip() == "%{":
                in_verbatim = True
                continue
            if raw.strip() == "%%":
                section = 1
                continue
            if raw.startswith("%define "):
                _, name, value = raw.split(None, 2)
                directives[name] = value.strip()
            elif raw.startswith("%"):
                directives[raw.strip().lstrip("%").split("=")[0]] = True
            continue
        if raw.strip() == "%%":
            break                      # trailing verbatim section, unused here
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        key, _, rest = raw.partition(",")
        keywords.append((key.strip(), rest.strip()))
    return directives, verbatim, keywords


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    d, verbatim, kw = parse(src)
    hash_name = d.get("hash-function-name", "gperf_hash")
    lookup = d.get("lookup-function-name", "gperf_lookup")
    icase = "ignore-case" in d
    # The struct is named by the last declaration before %%, which in every
    # NetSurf keyword file is `struct <name>;`.
    stype = "struct hash_entry"
    for line in verbatim + [l for l in open(src, encoding="utf-8")]:
        s = line.strip()
        if s.startswith("struct ") and s.endswith(";") and " " not in s[7:-1]:
            stype = "struct " + s[7:-1]
    # SORTED, because the lookup is a binary search. Case-insensitively when
    # asked, and the comparison at run time must use the same order or the
    # search walks past its own key.
    kw.sort(key=lambda e: e[0].lower() if icase else e[0])

    cmp_fn = "ns_strncasecmp" if icase else "strncmp"
    out = ["/* GENERATED by ports/netsurf/tools/nsgperf.py from %s -- do not edit. */"
           % src.split("/")[-1], ""]
    out += verbatim
    out += ["", "#include <stddef.h>", ""]
    if icase:
        out += [
            "static int ns_strncasecmp(const char *a, const char *b, size_t n)",
            "{",
            "\tfor (; n > 0; a++, b++, n--) {",
            "\t\tint ca = (*a >= 'A' && *a <= 'Z') ? *a + 32 : *a;",
            "\t\tint cb = (*b >= 'A' && *b <= 'Z') ? *b + 32 : *b;",
            "\t\tif (ca != cb) return ca - cb;",
            "\t\tif (ca == 0) break;",
            "\t}",
            "\treturn 0;",
            "}",
            "",
        ]
    # `wordlist` is gperf's own name for the %global-table, and callers use it
    # directly -- libhubbub walks it to turn a type back into a name. Ours is
    # DENSE where gperf's has hash gaps, so that reverse walk cannot land on an
    # empty slot and return its NULL name.
    out += ["static const %s wordlist[] = {" % stype]
    for name, value in kw:
        out.append('\t{ "%s", %s },' % (name, value))
    out += ["};", "",
            "#define NS_NWORDS (sizeof wordlist / sizeof wordlist[0])",
            ""]
    # gperf also emits a hash function; some callers reference it. Provide one
    # so a build that uses it still links, even though the lookup ignores it.
    out += [
        "static unsigned int %s(const char *str, size_t len)" % hash_name,
        "{",
        "\tunsigned int h = 2166136261u;",
        "\tfor (size_t i = 0; i < len; i++) {",
        "\t\tunsigned char c = (unsigned char)str[i];",
        ("\t\tif (c >= 'A' && c <= 'Z') c = (unsigned char)(c + 32);" if icase else ""),
        "\t\th = (h ^ c) * 16777619u;",
        "\t}",
        "\treturn h;",
        "}",
        "",
        "const %s *%s(const char *str, size_t len);" % (stype, lookup),
        "const %s *%s(const char *str, size_t len)" % (stype, lookup),
        "{",
        "\tsize_t lo = 0, hi = NS_NWORDS;",
        "\t(void)%s;" % hash_name,
        "\twhile (lo < hi) {",
        "\t\tsize_t mid = lo + (hi - lo) / 2;",
        "\t\tconst char *k = wordlist[mid].name;",
        "\t\t/* compare the whole candidate: a keyword that is a PREFIX of",
        "\t\t * another must not match the longer one, so length decides the",
        "\t\t * tie -- \"a\" and \"address\" both start with 'a'. */",
        "\t\tint c = %s(str, k, len);" % cmp_fn,
        "\t\tif (c == 0) {",
        "\t\t\tsize_t klen = 0;",
        "\t\t\twhile (k[klen] != '\\0') klen++;",
        "\t\t\tif (klen == len) return &wordlist[mid];",
        "\t\t\tc = (klen < len) ? 1 : -1;",
        "\t\t}",
        "\t\tif (c > 0) lo = mid + 1; else hi = mid;",
        "\t}",
        "\treturn NULL;",
        "}",
        "",
    ]
    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(l for l in out if l is not None) + "\n")


if __name__ == "__main__":
    main()
