/* GENERATED by tools/mkkeywords.py from EmbCC's lexer -- do not edit.
 *
 * Which words are C, taken from the compiler this OS ships, so the editor
 * and the compiler cannot disagree about it. The LEXING is deliberately not
 * shared: a compiler discards comments and refuses malformed input, and an
 * editor must colour both. See tools/mkkeywords.py.
 *
 * 39 keywords and 35 type names, from 50 entries in the compiler's table.
 */
#ifndef _EMBLINK_NOTE_CKEYWORDS_H_
#define _EMBLINK_NOTE_CKEYWORDS_H_

static const char *const C_KEYWORDS[] = {
    "_Static_assert", "_Generic", "_Alignof", "__alignof__", "__alignof",
    "_Alignas", "sizeof", "return", "static", "extern", "typedef", "const",
    "volatile", "__volatile__", "restrict", "asm", "__asm__", "inline",
    "__inline", "__inline__", "__attribute__", "__attribute", "if", "else",
    "while", "for", "break", "continue", "goto", "do", "switch", "case",
    "default", "_Noreturn", "_Thread_local", "_Complex", "_Imaginary",
    "register", "auto",
    0
};

static const char *const C_TYPES[] = {
    "int", "char", "short", "long", "float", "double", "_Bool", "typeof",
    "__typeof__", "__typeof", "_Atomic", "unsigned", "signed", "void",
    "struct", "union", "enum", "size_t", "ssize_t", "ptrdiff_t", "intptr_t",
    "uintptr_t", "bool", "true", "false", "NULL", "int8_t", "int16_t",
    "int32_t", "int64_t", "uint8_t", "uint16_t", "uint32_t", "uint64_t",
    "FILE",
    0
};

#endif
