#!/usr/bin/env python3
"""Generate user/note/ckeywords.h from EmbCC's lexer.

The editor highlights C, and the OS has a C compiler. Which words ARE C is a
fact that should have one owner, and the compiler is obviously it: a keyword
this OS's compiler accepts and the editor does not colour is a drift bug waiting
to happen, and vice versa.

What is NOT taken from the compiler is the lexing itself, and the reason is
worth writing down because it looks like the obvious thing to do. EmbCC's lexer
is the wrong SHAPE for an editor, in three ways that are not fixable by using
it more carefully:

  - it THROWS COMMENTS AWAY (skip_space_and_comments), and colouring comments is
    most of what a highlighter is for;
  - it calls diag_fatal on an unterminated comment, a bad escape, a malformed
    number -- correct for a compiler, fatal for an editor, because every file is
    malformed while you are still typing it;
  - it walks a whole translation unit from the top and allocates per token,
    where an editor must colour the fifty lines on screen, in any order, on
    every keystroke.

A compiler is allowed to refuse its input. An editor never is. So the lexers
stay separate and the WORD LIST is shared, which is the part that can actually
drift.

    python3 tools/mkkeywords.py           # regenerate
    python3 tools/mkkeywords.py --check   # fail if it would change

EmbCC is a separate repository, so this runs at development time and its output
is committed: myos must still build on a machine that has never heard of it.
"""
import os, re, sys

ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT    = os.path.join(ROOT, "user", "note", "ckeywords.h")
EMBCC  = os.environ.get("EMBCC_ROOT", os.path.join(os.path.dirname(ROOT), "EmbCC"))
LEX    = os.path.join(EMBCC, "src", "lex", "lex.c")

# Which token kinds name a TYPE rather than control flow or a storage class.
# The editor colours those differently, and the compiler's own token names are
# what say which is which.
TYPE_KINDS = {
    "TOK_KW_INT", "TOK_KW_CHAR", "TOK_KW_SHORT", "TOK_KW_LONG", "TOK_KW_FLOAT",
    "TOK_KW_DOUBLE", "TOK_KW_BOOL", "TOK_KW_UNSIGNED", "TOK_KW_SIGNED",
    "TOK_KW_VOID", "TOK_KW_STRUCT", "TOK_KW_UNION", "TOK_KW_ENUM",
    "TOK_KW_TYPEOF", "TOK_KW_ATOMIC",
}

# Words C has that this compiler does not implement. The editor still colours
# them: someone reading a file written elsewhere should see `_Thread_local` as a
# keyword rather than as a variable, even on a day EmbCC would reject it.
EXTRA_KEYWORDS = ["_Noreturn", "_Thread_local", "_Complex", "_Imaginary", "register", "auto"]
EXTRA_TYPES    = ["size_t", "ssize_t", "ptrdiff_t", "intptr_t", "uintptr_t",
                  "bool", "true", "false", "NULL",
                  "int8_t", "int16_t", "int32_t", "int64_t",
                  "uint8_t", "uint16_t", "uint32_t", "uint64_t", "FILE"]


def main():
    if not os.path.exists(LEX):
        print("mkkeywords: %s not present, keeping the committed header" % LEX)
        return 0
    src = open(LEX, encoding="utf-8", errors="replace").read()
    pairs = re.findall(r'\{\s*"([^"]+)"\s*,\s*(TOK_KW_[A-Z_]+)\s*\}', src)
    if not pairs:
        sys.exit("mkkeywords: no keyword table found in %s -- has it moved?" % LEX)

    kws, tys = [], []
    for word, kind in pairs:
        (tys if kind in TYPE_KINDS else kws).append(word)
    for w in EXTRA_KEYWORDS:
        if w not in kws: kws.append(w)
    for w in EXTRA_TYPES:
        if w not in tys: tys.append(w)

    def table(name, words):
        lines = ["static const char *const %s[] = {" % name]
        row = "   "
        for w in words:
            piece = ' "%s",' % w
            if len(row) + len(piece) > 76:
                lines.append(row); row = "   "
            row += piece
        lines.append(row)
        lines.append("    0")
        lines.append("};")
        return "\n".join(lines)

    out = ('/* GENERATED by tools/mkkeywords.py from EmbCC\'s lexer -- do not edit.\n'
           ' *\n'
           ' * Which words are C, taken from the compiler this OS ships, so the editor\n'
           ' * and the compiler cannot disagree about it. The LEXING is deliberately not\n'
           ' * shared: a compiler discards comments and refuses malformed input, and an\n'
           ' * editor must colour both. See tools/mkkeywords.py.\n'
           ' *\n'
           ' * %d keywords and %d type names, from %d entries in the compiler\'s table.\n'
           ' */\n'
           '#ifndef _EMBLINK_NOTE_CKEYWORDS_H_\n#define _EMBLINK_NOTE_CKEYWORDS_H_\n\n'
           % (len(kws), len(tys), len(pairs))) + \
          table("C_KEYWORDS", kws) + "\n\n" + table("C_TYPES", tys) + "\n\n#endif\n"

    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != out:
            sys.exit("ckeywords.h is out of date; run: python3 tools/mkkeywords.py")
        print("ckeywords.h up to date (%d keywords, %d types)" % (len(kws), len(tys)))
        return 0
    open(OUT, "w").write(out)
    print("wrote %s: %d keywords, %d types from EmbCC's %d-entry table"
          % (os.path.relpath(OUT, ROOT), len(kws), len(tys), len(pairs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
