#!/bin/bash
# ports/netsurf/build.sh -- cross-build NetSurf's libraries for EmbLinkOS.
#
# The source tree lives OUTSIDE this repo (like every other port here: see
# docs/PORTS.md). What lives inside is this script, the two host-tool
# replacements it puts on PATH, our patches, and the code we write ourselves --
# the fetcher, the frontend, and the compat shims.
#
#   NSSRC=... ports/netsurf/build.sh [component ...]
#
# With no arguments it builds the library stack in dependency order. The
# install prefix is inside the source tree, so nothing here touches /opt or
# needs a package manager.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NSSRC="${NSSRC:-/home/motsou/cross/netsurf/netsurf-all-3.11}"
PREFIX="${PREFIX:-$NSSRC/inst-emblink}"
HOST="${HOST:-x86_64-elf}"

[ -d "$NSSRC" ] || { echo "no NetSurf source at $NSSRC (set NSSRC=)" >&2; exit 1; }

# OUR host tools come first: this build machine has neither pkg-config nor
# gperf, and the port answers both itself rather than acquiring dependencies.
export PATH="$HERE/tools:$PATH"
export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
export NSSHARED="$PREFIX/share/netsurf-buildsystem"

# The libraries, in the order each one's headers are needed by the next.
LIBS=(libwapcaplet libparserutils libhubbub libcss libdom libnsgif libnsbmp
      libnsutils libutf8proc libnslog)

# WHAT THIS PORT TURNS OFF, and why. Each of these is a dependency we would
# otherwise have to port for something we do not need or already have.
component_flags() {
    case "$1" in
    libdom)
        # The XML bindings want expat or libxml2. A browser parses HTML with
        # hubbub; the XML path is for XHTML served as XML, which no page we
        # have ever loaded is. Turning it off removes expat from the port.
        echo "WITH_EXPAT_BINDING=no WITH_LIBXML_BINDING=no WITH_HUBBUB_BINDING=yes"
        ;;
    esac
}

build_one() {
    local lib="$1"
    echo "=== $lib"
    # shellcheck disable=SC2046  # the flags are deliberately word-split
    make -C "$NSSRC/$lib" install \
        PREFIX="$PREFIX" NSSHARED="$NSSHARED" HOST="$HOST" \
        COMPONENT_TYPE=lib-static \
        $(component_flags "$lib")
}

if [ ! -d "$NSSHARED" ]; then
    make -C "$NSSRC/buildsystem" install PREFIX="$PREFIX" >/dev/null
fi

# GPERF, without patching anything. The rule that runs it only fires when its
# output is missing or older than the .gperf, so generating the file here --
# with our own generator, verified against every keyword in the input -- means
# make never reaches for a tool this machine does not have. Zero patches is
# worth a few lines of script; see docs/PORTS.md on why that matters.
gen_gperf() {
    local in="$1" out="$2"
    [ -f "$in" ] || return 0
    if [ ! -f "$out" ] || [ "$in" -nt "$out" ] || [ "$HERE/tools/nsgperf.py" -nt "$out" ]; then
        echo "=== nsgperf $(basename "$in")"
        python3 "$HERE/tools/nsgperf.py" "$in" "$out"
    fi
}
gen_gperf "$NSSRC/libhubbub/src/treebuilder/element-type.gperf" \
          "$NSSRC/libhubbub/src/treebuilder/autogenerated-element-type.c"

declare -a EXTRA=()
targets=("$@")
[ ${#targets[@]} -eq 0 ] && targets=("${LIBS[@]}")
for l in "${targets[@]}"; do build_one "$l"; done

echo
echo "installed into $PREFIX/lib:"
ls -1 "$PREFIX"/lib/*.a 2>/dev/null | sed 's/^/  /'
